### ISSUE TITLE
`twee-lib-2.4.2` fails to build with GHC < 8.4

### ISSUE THREAD

**Issue by andreasabel** [nick8325/twee#9]
`twee-lib-2.4.2` fails to build with GHC < 8.4 because of a missing import.
```
Twee/Term/Core.hs:269:10: error:
    Not in scope: type constructor or class ‘Semigroup’
    |
269 | instance Semigroup (Builder f) where
    |          ^^^^^^^^^
```
I revised to `base >= 4.11` on hackage: https://hackage.haskell.org/package/twee-lib-2.4.2/revisions/

**Comment by nick8325** [comment]
Thanks, this should be fixed in future releases
