### ISSUE TITLE
Does not compile on GHC 9.2.1

### ISSUE THREAD

**Issue by emberdart** [nick8325/twee#4]
```
Data/Label.hs:124:38: error:
    • Couldn't match expected type ‘Int#’ with actual type ‘Int32#’
    • In the first argument of ‘findWorker’, namely ‘n#’
      In the expression: findWorker n#
      In an equation for ‘find’: find (Label !(I32# n#)) = findWorker n#
    |
124 | find (Label !(I32# n#)) = findWorker n#
    |                                      ^^

Data/Label.hs:130:18: error:
    • Couldn't match expected type ‘Int32#’ with actual type ‘Int#’
    • In the first argument of ‘I32#’, namely ‘n#’
      In the expression: I32# n#
      In an equation for ‘n’: n = I32# n#
    |
130 |     let n = I32# n#
    |                  ^^
```

Don't know about 9.0.1 yet though.

**Comment by emberdart** [comment]
This [section on breaking changes](https://github.com/fumieval/Haskell-breaking-changes/tree/d0ac926e8b5ca36f19570396d4b59a91c577784a#ongoing-word8) is the reason.

**Comment by jsynacek** [comment]
Fixed. See https://github.com/nick8325/twee/pull/6.

**Comment by emberdart** [comment]
Amazing. Thank you!
