### PR TITLE
Fix build with ghc-9.2.x

### LINKED ISSUE #4: Does not compile on GHC 9.2.1
```
Data/Label.hs:124:38: error:
    • Couldn't match expected type ‘Int#’ with actual type ‘Int32#’
    • In the first argument of ‘findWorker’, namely ‘n#’
      In the expression: findWorker n#
      In an equation for ‘find’: find (Label !(I32# n#)) = findWorker n#
    |
124 | find (Label !(I32# n#)) = findWorker n#
    |                                      ^^

Data/Label.hs:130:18: error:
    • Couldn't match expected type ‘Int32#’ with actual type ‘Int#’
    • In the first argument of ‘I32#’, namely ‘n#’
      In the expression: I32# n#
      In an equation for ‘n’: n = I32# n#
    |
130 |     let n = I32# n#
    |                  ^^
```

Don't know about 9.0.1 yet though.

### PR DESCRIPTION
**Pull request by jsynacek**
Fixes https://github.com/nick8325/twee/issues/4.

### CODE REVIEW

**Comment by jsynacek** [comment]
Superseded by https://github.com/nick8325/twee/pull/6.
